# Generated by Django 5.1 on 2024-10-08 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Equipment', max_length=100)),
                ('spoonacular_id', models.IntegerField(default=0, unique=True)),
                ('picture', models.URLField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='question',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Unnamed Ingredient', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='spoonacular_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_steps',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, upload_to='recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Unnamed Recipe', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='poster_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('description', models.TextField(default='No description provided')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='webpage.recipe')),
            ],
        ),
    ]
