# Generated by Django 5.1.1 on 2024-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_equipment_remove_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_steps',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='spoonacular_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
