# Generated by Django 5.1 on 2024-10-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_equipment_remove_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='spoonacular_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
