# Generated by Django 5.1 on 2024-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_recipe_spoonacular_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='webpage.ingredient'),
        ),
    ]
