# Generated by Django 5.1.1 on 2024-10-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_remove_recipe_cooking_steps_remove_recipe_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='spoonacular_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.equipment'),
        ),
        migrations.AlterField(
            model_name='ingredientslist',
            name='ingredients_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='poster_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
