# Generated by Django 5.1.1 on 2024-10-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_equipment_spoonacular_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsList',
            new_name='IngredientList',
        ),
        migrations.RenameField(
            model_name='equipmentlist',
            old_name='equipment_id',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='equipmentlist',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredientlist',
            old_name='ingredients_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientlist',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
