# Generated by Django 5.1 on 2024-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='picture',
            field=models.URLField(default='', null=True),
        ),
    ]
