# Generated by Django 5.1.2 on 2024-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_rename_ingredientslist_ingredientlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='spoonacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='spoonacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='spoonacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
