# Generated by Django 5.1.2 on 2024-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_recipe_poster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.URLField(default='', null=True),
        ),
    ]
