# Generated by Django 5.1.2 on 2024-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_alter_recipe_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
