# Generated by Django 5.1.2 on 2024-10-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('spoonacular_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.nutrition')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.recipe')),
            ],
        ),
    ]
