# Generated by Django 5.1.2 on 2024-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_alter_nutrition_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='unit',
        ),
        migrations.AlterField(
            model_name='nutritionlist',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
