# Generated by Django 5.1.1 on 2024-10-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_custom_diet_creation'),
        ('webpage', '0013_remove_nutrition_amount_remove_nutrition_unit_and_more'),
    ]

    operations = [
    ]
