# Generated by Django 5.1.2 on 2024-10-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_merge_20241021_1934'),
        ('webpage', '0014_merge_20241022_1207'),
    ]

    operations = [
    ]
