# Generated by Django 5.1.2 on 2024-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_merge_20241022_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
