# Generated by Django 5.1.2 on 2024-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='AI_status',
            field=models.BooleanField(default=False),
        ),
    ]
