# Generated by Django 5.1.2 on 2024-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0021_recipe_ai_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
