# Generated by Django 5.1.1 on 2024-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0023_alter_recipe_description_alter_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ManyToManyField(related_name='recipes', to='webpage.cuisine'),
        ),
    ]
