name: Code-Coverage

# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  DEBUG: True
  ALLOWED_HOSTS: '*'
  TIME_ZONE: 'Asia/Bangkok'
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  SPOONACULAR_PASSWORD: ${{secrets.SPOONACULAR_PASSWORD}}
  API_KEY: 'fake-key'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Coverage report
      run: |
        python -m coverage run manage.py test
        python -m coverage report
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
